// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IpLookupApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720093157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Country", b =>
                {
                    b.Property<string>("TwoLetterCode")
                        .HasColumnType("char(2)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("ThreeLetterCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.HasKey("TwoLetterCode");

                    b.HasIndex("ThreeLetterCode")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Ip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("CountryTwoLetterCode")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("CountryTwoLetterCode");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("CountryTwoLetterCode")
                        .HasDatabaseName("IX_IpAddress_CountryTwoLetterCode_UpdatedAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CountryTwoLetterCode"), new[] { "UpdatedAtUtc" });

                    b.ToTable("IpAddress", (string)null);
                });

            modelBuilder.Entity("JobHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FinishedAt");

                    b.Property<int>("ProcessedRecords")
                        .HasColumnType("int")
                        .HasColumnName("ProcessedRecords");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<int>("UpdatedRecords")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedRecords");

                    b.HasKey("Id");

                    b.ToTable("JobHistory", (string)null);
                });

            modelBuilder.Entity("Ip", b =>
                {
                    b.HasOne("Country", null)
                        .WithMany()
                        .HasForeignKey("CountryTwoLetterCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
